PEARS/PEARS/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^track/pizzas/', include("apps.pizza.urls", namespace='pizzas')),
    url(r'^admin/', admin.site.urls),
    ]

PEARS/apps/pizza/urls.py
from django.conf.urls import url

from .views import pizza_list, pizza_detail, pizza_create,\
    toppings_create, pizza_update, pizza_delete

urlpatterns = [
    url(r'^$', pizza_list, name='pizzas'),
    url(r'^(?P<id>\d+)/$', pizza_detail, name='detail'),
    url(r'^create/$', pizza_create, name='pizza_create'),
    url(r'^create_toppings/$', toppings_create, name='toppings_create'),
    url(r'^(?P<id>\d+)/edit/$', pizza_update, name='update'),
    url(r'^(?P<id>\d+)/delete/$', pizza_delete, name='delete'),
]

PEARS/apps/pizza/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

# Create your models here.

class Pizza(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,)
    organization = models.CharField(max_length=150)
    reporting_period = models.DateField(auto_now=False, auto_now_add=False)
    name = models.CharField(max_length=100)
    toppings = models.ManyToManyField('Topping')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('pizzas:detail', kwargs={'id': self.id})

class Topping(models.Model):
    toppings_name = models.CharField(max_length=150)

    def __str__(self):
        return self.toppings_name

PEARS/apps/pizza/forms.py
from django import forms
from . models import Pizza, Topping

class PizzaForm(forms.ModelForm):
    class Meta:
        model = Pizza
        fields = [
            'user',
            'organization',
            'reporting_period',
            'name',
            'toppings',
        ]

class ToppingForm(forms.ModelForm):
    class Meta:
        model = Topping
        fields = [
            'toppings_name',
        ]

PEARS/apps/pizza/views.py
from django.shortcuts import render, get_object_or_404
from . models import Pizza, Topping
from django.contrib.auth.models import User
from .forms import PizzaForm, ToppingForm
from django.http import HttpResponseRedirect

# Create your views here.

def pizza_list(request):
    user_filter = request.GET.get('u')
    rp_filter = request.GET.get('rp')
    tp_filter = request.GET.get('t')
    if user_filter:
        queryset = Pizza.objects.filter(user__username=user_filter)

    elif rp_filter:
        queryset = Pizza.objects.filter(reporting_period=rp_filter)

    elif tp_filter:
        queryset = Pizza.objects.filter(toppings__toppings_name=tp_filter)
    else:
        queryset = Pizza.objects.all()
    context = {
        'pizzas': queryset,
        'users': User.objects.all(),
        'toppings': Topping.objects.all(),
    }
    return render(request, 'index.html', context)


def pizza_detail(request, id):
    instance = get_object_or_404(Pizza, id=id)
    context = {
        'instance': instance,
    }
    return render(request, 'pizza_detail.html', context)

def pizza_create(request):
    form = PizzaForm(request.POST or None)
    if rquest.method == 'POST':
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            form.save_m2m()
            return HttpResponseRedirect('/pizzas')
    context = {
        'form': form
    }
    return render(request, 'pizza_form.html', context)

def toppings_create(request):
    form = ToppingForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid:
            instance = form.save(commit=False)
            instance.save()
            return HttpResponseRedirect('/pizzas')
    context = {
        'form': form
    }
    return render(request, 'toppings_form.html', context)

def pizza_update(request, id=None):
    instance = get_object_or_404(Pizza, id=id)
    form = PizzaForm(request.POST or None, instance=instance)
    if request.method == 'POST':
        if form.is_valid:
            instance = form.save(commit=False)
            instance.save()
            form.save_m2m()
            return HttpResponseRedirect(instance.get_absolute_url())
    context = {
        'instance': instance,
        'form': form,
    }
    return render(request, 'pizza_form.html', context)

def pizza_delete(request, id=None):
    instance = get_object_or_404(Pizza, id=id)
    instance.delete()
    messages.success(request, "Successfully Deleted!")
    return HttpResponseRedirect('/pizzas')

PEARS/templates/index.html
<!DOCTYPE html>
<html lang="en">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <h1>Welcome To Pizzeria</h1>

    <h3>Filter Results By:</h3>

    <div class="user_filter">
         <form class="navbar-form navbar-left" role="search" method="get" action="">
              <div class="form-group">
                    <b>By User: </b>
                    <select name="u">
                        {% for user in users %}
                           <option value="{{ user }}">{{ user }}</option>
                        {% endfor %}
                    </select>
                </div>
                <input type="submit" class="btn btn-default"></input>
         </form>
    </div>

    <div class="rp_filter">
         <form class="navbar-form navbar-left" role="search" method="get" action="">
              <div class="form-group">
                    <b>By Reporting period: </b>
                    <input type="date" name="rp">
                </div>
                <input type="submit" class="btn btn-default"></input>
         </form>
    </div>

    <div class="toppings_filter">
         <form class="navbar-form navbar-left" role="search" method="get" action="">
              <div class="form-group">
                    <b>By Toppings: </b>
                    <select name="t">
                        {% for topping in toppings %}
                           <option value="{{ topping }}">{{ topping }}</option>
                        {% endfor %}
                    </select>
                </div>
                <input type="submit" class="btn btn-default"></input>
         </form>
    </div>

    <div class="no_filter">
        <form class="navbar-form navbar-left" role="search" method="get" action="">
            <div class="form-group">
                <b>Show ALL</b>
            </div>
            <input type="submit" class="btn btn-default"></input>
        </form>
    </div>

    <br><br>
    <h5><a href="{% url 'pizzas:pizza_create' %}">Click Here To Add A New Pizza</a></h5>
    <h5><a href="{% url 'pizzas:toppings_create' %}">Click Here To Add a New Topping</a></h5>
    <table class="table">
                        <thead>
                        <tr>
                            <th>NAME</th>
                            <th>USER</th>
                            <th>ORGANIZATION</th>
                            <th>REPORTING PERIOD</th>
                            <th class="text-right">TOPPINGS</th>
                        </tr>
                        </thead>

                        {% for pizza in pizzas %}
                            <tr>
                                <td><a href="{{ pizza.get_absolute_url }}">{{ pizza.name }}</td></a>
                                <td>{{ pizza.user }}</td>
                                <td>{{ pizza.organization }}</td>
                                <td>{{ pizza.reporting_period }}</td>
                                {% for topping in pizza.toppings.all %}<td>{{ topping }}</td><br/>{% endfor %}

                            </tr>
                        {% endfor %}
    </table>

</head>
<body>

</body>
</html>

PEARS/templates/pizza_detail.html
<html>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <body>
        <h1>{{ instance.name }}</h1>
        <b>User : </b> {{ instance.user }} </br>
        <b>Organization : </b> {{ instance.organization }} </br>
        <b>Reporting_Period: </b> {{ instance.reporting_period }}</br></br>
        <b>Toppings: </b> </br>{% for topping in instance.toppings.all %}{{ topping }}<br/>{% endfor %}
        <br>
        <a href="/pizzas/{{ instance.id }}/edit">Edit</a>
        <br>
        <a href="/pizzas/{{ instance.id }}/delete">Delete</a>
    </body>
</html>

PEARS/templates/pizza_form.html
<!DOCTYPE html>
<html lang="en">

<body>

    <h1>Add New Pizza</h1>
    <form method="POST" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Create" />
    </form>
</body>
</html>

PEARS/templates/toppings_form.html
<!DOCTYPE html>
<html lang="en">

<body>

    <h1>Add New Topping</h1>
    <form method="POST" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Add" />
    </form>
</body>
</html>